
#ifndef CS4544REEAL_CONSTANTS_H
#define CS4544REEAL_CONSTANTS_H
#define MAXHOSTNAME 64
#define BINDERPORT 52016
#define SERVERPORT 0
#define MAXFUNCNAME 64

#define ARG_CHAR    1
#define ARG_SHORT   2
#define ARG_INT     3
#define ARG_LONG    4
#define ARG_DOUBLE  5
#define ARG_FLOAT   6

#define ARG_INPUT   31
#define ARG_OUTPUT  30


#endif //CS4544REEAL_CONSTANTS_H
