#ifndef ERROR
#define ERROR



//RPC CONNECTION ERRORS
#define ERR_CREATE_SOCK_SERVER_FAIL -1
#define ERR_BINDER_CONNECT_FAIL -2

//RPC CLIENT ERRORS
#define ERR_PROCEDURE_NOT_FOUND -3


//RPC SERVER ERRORS
#define ERR_REG_FAIL -4
#define ERR_REG_RESPONSE_FAIL -5


#define ERR_BINDER_SERVER_RECV_FAIL -6
#define ERR_BINDER_SERVER_SEND_FAIL -7

// BINDER DB ERRORS
#define ERR_INSERT_BINDER_DB -8


#define ERR_SERVER_NOT_FOUND -9
#define ERR_SERVER_CLIENT_RECV -10

#define ERR_SERVER_DOESNT_CONTAIN_FUNC -12

#define ERR_INVALID_ARGS -13
#define ERR_RECV_CLIENT -14

#define ERR_TERMINATING -15

#define ERR_SENDING_REG -16
#define ERR_SKEL_NOT_FOUND -17
#define ERR_SENDING_EXEC_RESP -18
#define ERR_SENDING_LOC_REQ -19
#define ERR_CLIENT_SERVER_CONNECT_FAIL -20
#define ERR_SENDING_EXEC_REQ -21

#define ERR_EXECUTE_FAIL -22


#define ERR_BINDER_REG_FAIL -23

#define ERR_LOC_REQ_FAIL -24
#define ERR_LOC_RESP_FAIL -25

#define ERR_SOCKET_CONNECT_FAIL -27

#define ERR_SELECT_FAIL -28
#define ERR_BINDER_ACCEPT_FAIL -29
#define ERR_BINDER_DB_UPDATE_FAIL -30
#define ERR_BINDER_RECV_FAIL -31
#define ERR_INVALID_MSG_TYPE -26


#define ERR_SERVER_ACCEPT_FAIL -32
#define ERR_SERVER_RECV_FAIL -33

#define ERR_MSG_TYPE_NOT_FOUND -34

#define ERR_UNMARSHALL_FAIL -35

#endif