#ifndef ERROR
#define ERROR



//RPC CONNECTION ERRORS
#define ERR_CREATE_SOCK_FAIL -1
#define ERR_BINDER_CONNECT_FAIL -2

//RPC CLIENT ERRORS
#define ERR_PROCEDURE_NOT_FOUND -3


//RPC SERVER ERRORS
#define ERR_REG_FAIL -4
#define ERR_REG_RESPONSE_FAIL -5


#define ERR_BINDER_RECV_FAIL -6
#define ERR_BINDER_SEND_FAIL -7

// BINDER DB ERRORS
#define ERR_INSERT_BINDER_DB -8


#define ERR_SERVER_NOT_FOUND -9
#define ERR_SERVER_CLIENT_RECV -10
#endif