#ifndef ERROR
#define ERROR

//GENERAL ERRORS
#define ERR_RECV_FAIL -6

//RPC CONNECTION ERRORS
#define ERR_CREATE_SOCK_FAIL -1
#define ERR_BINDER_CONNECT_FAIL -2

//RPC CLIENT ERRORS
#define ERR_PROCEDURE_NOT_FOUND -3


//RPC SERVER ERRORS
#define ERR_REG_FAIL -4
#define ERR_REG_RESPONSE_FAIL -5
#define ERR_FUNC_DEFINED 5



#endif